#!/bin/sh

adgh=false
mosdns=false
dns_hijack=auto
# mosdns / adgh / clash / auto
# mosdns只认第一个udp服务器监听,auto会看开关状态来选,adgh>mosdns>clash

ipv6="disable"

proxy_method="TPROXY"
# REDIRECT: TCP only / TPROXY: TCP + UDP / MIXED: REDIRECT TCP + TUN UDP

proxy_mode="blacklist"
# blacklist / whitelist / core
user_packages_list=()
# Android User:Package Name, For example:
# user_packages_list=("0:com.android.captiveportallogin" "10:com.tencent.mm")

ap_list=("wlan+" "ap+" "rndis+")
ignore_out_list=()

bin_name="clash"
path=$(cd $(dirname `realpath $0`); cd ../; pwd)
bin_path="${path}/bin/${bin_name}"
run_path="${path}/run"
pid_file="${run_path}/${bin_name}.pid"

tun_device="tun0"

user_group="root:net_admin"

intranet=(0.0.0.0/8 10.0.0.0/8 100.64.0.0/10 127.0.0.0/8 169.254.0.0/16 192.0.0.0/24 192.0.2.0/24 192.88.99.0/24 192.168.0.0/16 198.51.100.0/24 203.0.113.0/24 224.0.0.0/4 240.0.0.0/4 255.255.255.255/32)
intranet6=(::/128 ::1/128 ::ffff:0:0/96 100::/64 64:ff9b::/96 2001::/32 2001:10::/28 2001:20::/28 2001:db8::/32 2002::/16 fe80::/10 ff00::/8)
